### PR TITLE
Update sundials interface reflecting changes in sundialsml.

### PR DESCRIPTION
**Pull request by br4sco**

### CODE REVIEW

**Comment by david-broman** [comment]
Good. Can you describe which version that has changed (only Sundials ML)? Is another version of Sundials supported now? These things have implications on macOS installations.

**Comment by br4sco** [comment]
So this is [sundialsml v4.1.0p0](https://github.com/inria-parkas/sundialsml/releases/tag/v4.1.0p0) which I have tested against [sundials 4.1.0](https://computing.llnl.gov/projects/sundials/sundials-software). We might want to hold off on merging this since the current sundialsml version in opam is 3.1.1. The reason I updated was that I had trouble getting the opam version working on my Fedora 32 system.

**Comment by david-broman** [comment]
Should this PR perhaps be changed to a DRAFT PR?

**Comment by br4sco** [comment]
> Should this PR perhaps be changed to a DRAFT PR?

I cannot, but I'll close it instead.

**Pull request closed without merging**
