### PR TITLE
Add .editorconfig

### PR DESCRIPTION
**Pull request by br4sco**
Rather than just specify code formating in the wiki I suggest that we add an https://editorconfig.org/ configuration with our specification. The benefit is that many editors has builtin support for editorconfig (and even more have optional plugins), meaning that they will automatically indent code etc. according to our specification when editing files in this repo.

### CODE REVIEW

**Comment by johnwikman** [comment]
I generally like this, but the root directory is becoming really crowded now. Can this file replace other things? Such as `mcore-comby.json`, `.ocamlformat`, etc.

**Comment by br4sco** [comment]
It is more general (in the sense that it is agnostic to the language), but it only governs indentation style and whitespace. It cannot replace ocamlformat, which is a full-fledges code formatter, for example. I still think this is better than only specifying this in the wiki (as we do now).

**Comment by br4sco** [comment]
Regarding `.ocamlformat`, we could move that to the `src/boot` where the OCaml code lives.

**Comment by johnwikman** [comment]
By the way, could we perhaps have this file format as an interface for pretty printing in the future as well? I.e. the pretty printer uses a editorconfig config (a default setting or loaded from file) to determine the style of the output.

Something like `mi fmt <file>` would then look for an .editorconfig file to determine how it should pretty print the program.

From the spec ([link](https://spec.editorconfig.org/#id11)):
> EditorConfig plugins shall ignore unrecognized keys and invalid/unsupported values.

So I guess that we can add basically any additional information we need to a .editorconfig file?

**Pull request merged**
