### PR TITLE
Sequence based vector, matrix and set libraries 

### PR DESCRIPTION
**Pull request by br4sco**
These libraries implements set, vector and matrix operations over sequences.

### CODE REVIEW

**Comment by johnwikman** [comment]
This is more of a comment regarding matrix representation in general than about the implementation. When I perform GPU optimized matrix operations in MCore I rely on the fact that the matrix is represented as flat sequence of elements. Then I adjust the indexing when accessing the individual elements. In a way, the type looks like this for me:
```
type Matrix a = {rows : Int, cols : Int, v : [a]}
```
In the case of the sequence in sequence representation, if we were to perform matrix multiplication with 4000x4000 matrices on a GPU we would have to either flatten them first or perform ~12000 individual memcpys (2 input + 1 output matrix). On the other hand it would be more efficient to perform operations such as swapping rows by using the sequence in sequence representation.

**Comment by br4sco** [comment]
> This is more of a comment regarding matrix representation in general than about the implementation. When I perform GPU optimized matrix operations in MCore I rely on the fact that the matrix is represented as flat sequence of elements. Then I adjust the indexing when accessing the individual elements. In a way, the type looks like this for me:
> 
> ```
> type Matrix a = {rows : Int, cols : Int, v : [a]}
> ```
> 
> In the case of the sequence in sequence representation, if we were to perform matrix multiplication with 4000x4000 matrices on a GPU we would have to either flatten them first or perform ~12000 individual memcpys (2 input + 1 output matrix). On the other hand it would be more efficient to perform operations such as swapping rows by using the sequence in sequence representation.

I see. I could hide the matrix implementation from the interface, which is  a good thing in general. I didn't bother now since this is anyways temporary, but if this library is something we both could use I don't mind changing the implementation.

**Comment by br4sco** [comment]
Thinking a little about I think I will remove the vector library and just define a matrix library to keep this as slim as possible.

**Comment by johnwikman** [comment]
> > This is more of a comment regarding matrix representation in general than about the implementation. When I perform GPU optimized matrix operations in MCore I rely on the fact that the matrix is represented as flat sequence of elements. Then I adjust the indexing when accessing the individual elements. In a way, the type looks like this for me:
> > ```
> > type Matrix a = {rows : Int, cols : Int, v : [a]}
> > ```
> > 
> > 
> > In the case of the sequence in sequence representation, if we were to perform matrix multiplication with 4000x4000 matrices on a GPU we would have to either flatten them first or perform ~12000 individual memcpys (2 input + 1 output matrix). On the other hand it would be more efficient to perform operations such as swapping rows by using the sequence in sequence representation.
> 
> I see. I could hide the matrix implementation from the interface, which is a good thing in general. I didn't bother now since this is anyways temporary, but if this library is something we both could use I don't mind changing the implementation.

I only needed a few matrix functions to run some benchmarks, so do not worry about me! I was more concerned about the future non-temporary implementation, but maybe it is too early to discuss that now.

**Comment by lingmar** [comment]
Looks good to me!

**Pull request merged**
