### PR TITLE
Custom pretty printing in utests

### PR DESCRIPTION
**Pull request by br4sco**
This PR adds the option to supply a function that specifies the output string for the left-hand and right-hand sides of failing utests. The semantics and syntax are best described with an example. The following code snippet:

```
...
mexpr
let eq : Int -> String -> Bool = lam l. lam r. eqi 0 (string2int r) in
let toString : Int -> String -> String = lam l. lam r.
  join ["left hand: ", int2string l, ", right hand: \"", r, "\""]
in
utest 0 with "1" using eq in               -- Failing
utest 0 with "1" using eq else toString in -- Failing
utest 0 with "0" using eq else toString in -- Passing
()
```

will on execution output:

```
 ** Unit test FAILED: <fileinfo> **
    LHS: 0
    RHS: ['1']
    Using: eq

 ** Unit test FAILED: <fileinfo> **
left hand: 0, right hand: "1"
    Using: eq
.ERROR! 1 successful tests and 2 failed tests.
```
 
The else function has the signature `a -> b -> String` and is only applied to the left-hand side and the right-hand side if a test fails (the standard formatting is omitted in this case). Currently, you always have to specify the custom equality function if you want to also specify the else function due to how the bootparser is implemented. We can relax this later on if we want to.
This PR addresses https://github.com/miking-lang/miking/issues/677.

You can find the above example in [test/examples/utest/utest-with-onfail.mc](https://github.com/miking-lang/miking/commit/92f56c8491aa75bc523fcf98cc878e64b35f5040#diff-af7d058521a4b491cc049871147b55496c02287e98f89adae9d1e658a1622dbe).

### CODE REVIEW

**Comment by johnwikman** [comment]
Looks good! But I would also like to have the option to get `LHS: ... RHS: ...` formatting for free, i.e. that I just provide string conversion on either side:
```
let toString : Int -> String -> (String, String) =
    lam l. lam r. (int2string l, concat "strint: " r)
in
utest 0 with "1" using eq onfail toString in
-- This would output
-- ** Unit test FAILED: <fileinfo> **
--    LHS: 0
--    RHS: strint: 1
--    Using: eq

-- or even more convenient
utest 0 with "1" using eq onfail (int2string, concat "strint: ") in
```

**Comment by br4sco** [comment]
I propose that we implement that functionality as a library function `defaultOnfail : all a. all b. (a -> String) -> (b -> String) -> a -> b -> String` rather than adding more keywords and variations on the `utest` term. Or do you want to replace the current signature so that "RHS:" and "LHS:" are always printed?

**Comment by johnwikman** [comment]
Yes that sounds like a good solution. Can probably be part of a separate PR then

**Comment by br4sco** [comment]
Changed `onfail` to `else`.

**Pull request closed without merging**
